version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask:
    build:
      context: ./flask  # flaskディレクトリがビルドコンテキストとなる
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      FLASK_ENV: development

  react:
    build: ./react  # reactディレクトリをビルドコンテキストとする
    ports:
      - "3000:3000"
    depends_on:
      - flask

volumes:
  db_data:
